version: '3.8'

services:
  dptb:
    build: .
    container_name: dptb-app
    ports:
      - "9155:9000"
    volumes:
      - ./profiles:/app/profiles
    environment:
      - PYTHONIOENCODING=utf-8
      - TZ=Etc/UTC
    restart: unless-stopped
